import type { NextPage } from 'next';
import Head from 'next/head';

const Communities: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Twitter UI Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>communities</p>
    </div>
  );
};

export default Communities;
