import type { NextPage } from 'next';
import Head from 'next/head';
import useSWR from 'swr';
import Tweet from '../components/Tweet';

const fetcher = (url: string) => fetch(url).then((res) => res.json());

const Home: NextPage = () => {
  const { data, error } = useSWR<Tweet[]>('/api/tweets?limit=20', fetcher);

  if (error) return <div>failed to load</div>;
  if (!data) return <div>loading...</div>;

  return (
    <div>
      <Head>
        <title>Home / Twitter UI Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {data.map(
        ({ id, profile_pic, username, name, tweet, tweet_at }, index) => (
          <Tweet
            key={id}
            profile_pic={profile_pic + index}
            username={username}
            name={name}
            tweet={tweet}
            tweet_at={tweet_at}
          />
        )
      )}
    </div>
  );
};

export default Home;
