import type { NextPage } from 'next';
import Head from 'next/head';

const Messages: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Message / Twitter UI Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>messages</p>
    </div>
  );
};

export default Messages;
