import type { NextPage } from 'next';
import Head from 'next/head';

const Notifications: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Notifications / Twitter UI Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>notifications</p>
    </div>
  );
};

export default Notifications;
